NannyML/The-Little-Book-of-ML-Metrics

book/4-clustering.tex

#51 
Added Silhouette score first page.
Appreciate any reviews and recommendations.

 Silhouette Score #51 First Page

---

book/6-computer-vision.tex

I have added the first page for PSNR metrics.
I am very appreciate for reviews and recommendations. Many thanks

PSNR Peak-Signal-to-Noise Ratio #91 First Page

---

book/11-business.tex

I've completed the Conversion Rate metric section and am open to any feedback, changes, or further assistance.

Added Conversion Rate metric

---

.gitignore
book/2-regression.tex

Hi 
I am adding the MSE formula in this pull request here. 
If you have any further request, please give me the comment. I am very appreciate 
Thank you 
Duy

Update MSE and MAPE formula 

---

book/2-regression.tex

add RMSLE formula

---

book/6-computer-vision.tex

Spelling mistake

---

book/2-regression.tex

Please feel free to point out any necessary changes. Attached is how it looks like.

included sMAPE formula

---

book/2-regression.tex
book/main.tex

This PR adds the formula for the Mean Directional Accuracy in the regression section.

Added MDA formula

---

book/2-regression.tex

Added the MPD formula to the 2-regression.tex file.

Added MPD formula

---

book/3-classification.tex

**Closes**: #140
This PR adds an accuracy formula to the classification section.  Added formula will look like:

Added accuracy formula

---

book/2-regression.tex

**Closes**: #126 
This PR adds D2 Absolute Score to the Regression Section. The compiled formula looks as:

Added D2 Absolute Score Formula

---

book/3-classification.tex

This PR adds F-beta score formula to the classification section. The compiled formula looks like

Added F-beta score formula

---

book/2-regression.tex
book/3-classification.tex

**Closes** #143   
***This PR Adds F1 Score Formula to the Classification Section.***
****The Compiled Formula Look like as this:****
:)

Adding F1 Score Formula

---

book/3-classification.tex

Added precision formula in the classification section

Added Precision Formula

---

book/2-regression.tex

Added MASE formula in Regression section.

Added MASE formula

---

book/3-classification.tex

Adding ROC-AUC formula 

---

book/3-classification.tex

This PR completes to add the ROC-AUC formula. 
Note: Extended the formula to two lines to make sure it fits the page, as colored boxes will not fit in the same page.

Added ROC-AUC formula

---

book/3-classification.tex

This PR adds the Brier Score Loss formula to the Classification Section. Additionally, extended the formula to multi-class classification.

Added Brier Score Loss Formula

---

book/3-classification.tex

This PR adds the Log Loss formula to the classification section.

Added Log Loss Formula

---

book/3-classification.tex

Adding Jaccard Index Formula.
closes #158 
Screenshot:

Adding Jaccard Index Formula

---

book/3-classification.tex

Fixes #173 
I've added the general notation of the formula as described in the issue. Please let me know if any further corrections are needed and I will make the necessary changes.
cc: @santiviquez

Add General Notation of Jaccard Index Formula
